Traceback (most recent call last):
  File "/Users/liujiyao/miniforge3/envs/torchcpu/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/liujiyao/miniforge3/envs/torchcpu/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/liujiyao/miniforge3/envs/torchcpu/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/liujiyao/miniforge3/envs/torchcpu/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/liujiyao/miniforge3/envs/torchcpu/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/liujiyao/miniforge3/envs/torchcpu/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/liujiyao/miniforge3/envs/torchcpu/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
class MyBN:
    def __init__(self, momentum=0.9, eps, n_features):
        self._momentum = momentum
        self._eps = eps
        self._running_mean = 0
        self._running_var = 1
        self._beta = np.zeros(shape=(n_features,))
        self._gamma = np.ones(shape=(n_features,))
        
   def batch_norm(self, x):
        mu = x.mean(axis=0)
        var = v.var(axis=0)
        self.runing_mean = (1-self._momentum)*mu + self._momentum*self._running_mean
        self.runing_var = (1-self._momentum)*var + self._momentum*self._running_var
        x_hat = (x - mu) / np.sqrt(var + self._eps)
        y = self._gamma * x_hat + self._beta
        
       return y
------------------


[0;36m  File [0;32m<tokenize>:10[0;36m[0m
[0;31m    def batch_norm(self, x):[0m
[0m    ^[0m
[0;31mIndentationError[0m[0;31m:[0m unindent does not match any outer indentation level


